language: node_js
node_js:
  - "14"

services:
  - docker

before_install:
  - docker build -t digistorepos .
  - docker images

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
